#Preprocesamiento de dos variables independientes
##AFRICA: Derechos de Propiedad y Libertad de Inversión
```{r}
library(readr)
Libertades_economicas_Africa <- read_csv("Libertades economicas-Africa.csv")

#cambiamos de nombre a la data
africa <- Libertades_economicas_Africa  

names(africa)
#eliminamos columnas innecesarias
africa[,c(2:3)] = NULL
names(africa)
africa[,c(3:11)] = NULL
names(africa)
africa$`Financial Freedom` = NULL

#cambiamos nombres
names(africa) = c("Pais", "Derechos_Propiedad","Libertad_Inversion")

#convertir a numérica
str(africa)
africa[,-1]=lapply(africa[,-1], as.numeric)

#verificamos NA
africa[!complete.cases(africa),] 

#eliminamos espacios en blanco
africa$Pais <- trimws(africa$Pais,whitespace = "[\\h\\v]") 
africa$Derechos_Propiedad <- trimws(africa$Derechos_Propiedad ,whitespace = "[\\h\\v]") 
africa$Libertad_Inversion <- trimws(africa$Libertad_Inversion ,whitespace = "[\\h\\v]") 
View(africa)
```


##EUROPA: Derechos de Propiedad y Libertad de Inversión
```{r}
library(readr)
Libertades_economicas_Europa <- read_csv("Libertades economicas-Europa.csv")
europa <- Libertades_economicas_Europa 

#eliminamos columnas innecesarias
names(europa)
europa[,c(2:3)] = NULL
names(europa)
europa[,c(3:11)] = NULL
europa$`Financial Freedom` = NULL

#cambiamos nombres
names(europa) = c("Pais", "Derechos_Propiedad","Libertad_Inversion")

#convertir a numérica
str(europa)
europa$Derechos_Propiedad <- as.numeric(europa$Derechos_Propiedad)

#verificamos NA
europa[!complete.cases(europa),] 

#eliminamos espacios en blanco
europa$Pais <- trimws(europa$Pais,whitespace = "[\\h\\v]") 
europa$Derechos_Propiedad  <- trimws(europa$Derechos_Propiedad  ,whitespace = "[\\h\\v]") 
europa$Libertad_Inversion <- trimws(europa$Libertad_Inversion ,whitespace = "[\\h\\v]") 
View(europa)
```



##Preprocesamiento de la variables dependiente Religión

```{r}
install.packages("htmltab")
library(htmltab)

link_wik="https://en.wikipedia.org/wiki/Importance_of_religion_by_country"

linkPath_wik='//*[@id="mw-content-text"]/div/table'

religion=htmltab(doc=link_wik, which=linkPath_wik)

head(religion)
```

##exploramos la data
```{r}
names(religion)
str(religion)
```

#Seleccionamos los paises de Europa y Africa (en la lista de los 50 primeros, todos eran de Europa)
```{r}
#el ultimo pais que me toca editar es Grecia (31)

religion4 <- religion[-c(6,7),] #restarle uno a todo

religion2 <- religion[-c(6,7,10,12,14,16,25,27,29,30,31,37,41,42,43,44,46,47,48),]
View(religion2)

#eliminamos japon, honk kong, vietnam, Australia, Nueva Zelanda,Cuba,Uruguay,canada,corea del sur, kazajistan, taiwan, israel,uzbekistan, belice,argentina, estados unidos, chile,singapur, jamaica

#elimino el resto de paises de la tabla hasta la 149
religion3 <- religion2[-c(32:149),]
View(religion3)

```

```{r}
#cambiamos los nombres de las columnas
names(religion3) = c("Pais","Importante","NoImportante")
```


#limpiamos la data
```{r}
install.packages("readr")
library(readr)
religion3$Importante <- parse_number(religion3$Importante)
religion3$NoImportante <- parse_number(religion3$NoImportante)

#convertimos a numericas
str(religion3)
religion3[,-1]=lapply(religion3[,-1], as.numeric)

#eliminamos los espacios en blanco
religion3$Pais=trimws(religion3$Pais,whitespace = "[\\h\\v]")
religion3$Importante=trimws(religion3$Importante,whitespace = "[\\h\\v]")
religion3$NoImportante=trimws(religion3$NoImportante,whitespace = "[\\h\\v]")
head(religion3)
View(religion3)
```
```

